language: ruby
rvm:
- 2.2.5
before_install:
- sudo apt-get install -y openconnect
- sudo apt-get install -y sshpass
script: ./_scripts/cibuild
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USER=natew
  - local_src="_site/"
  - remote_host="pyrite.cs.iastate.edu"
  - remote_dest="/home/natew/TRAVIS_TESTS"
  - secure: e47oTdWCic0SsJuFBnhDdd4OsUW419Gdp57UCc1W47LuTbZLoksT7k0YpDqU9kbFIP3bQhcp91lKyS8BFEKiPw/0Dmq+ryV8/Ie2aE65rkAHvimgDJZO1pm4XfHFPFaVfAUrTaeA/RwEcR25nSMCiz0xHDBNtIndyE1KhSDIew3lG0XATenzAfjJAJ3EeVxGpIx4hyfMGzAt+bkM+4y5Els5+u/pBRc6Ikaak+HQGdmDaTQfnnvSWQ+s9VU3YijHC4vyQ6gpJ2sIaIAgNnPugMagbYHqgeoiqChtsytfmC7UIX4osd3ZGebkuoce48WyQrnouFlaVmCaxkgZijoTrfnhZjSrEMP+97mPkQLodaOS4g7nMIiAP85ffwIAwAhO4GmtUeyvHAH0SljvpGhUJ2PFRIBfS0h8ASgVX6Gv92S2mmKGebZ6Fc8lz5pzq6XH4odvKU3iUdEfkLfZ9jFp3GMv63E1nqBw8HmEj5/GC68pNYGqLJR85EtfBLAnnqsbsSxmHb4EGsb7qtHe/novIoUxIwyVZq1RZjqRwtw6kAmGKOLkSFRVcL4RYkW+QqaiH+0ZLBaDEnOfzg6oGF+gn3wikTis8q1xT5kREAi5SuN5zo6mUuXx3dtdjODdzSthbfAfX9xffoSvuQBRwPub2lSerC1n6afkuDtBJgdMvzM=
sudo: required
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./_scripts/deploy/automatically.sh
  on:
    branch: feature/travisCI
